[2023-05-11T18:58:39.365+0000] {processor.py:153} INFO - Started process (PID=190) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T18:58:39.366+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T18:58:39.366+0000] {logging_mixin.py:137} INFO - [2023-05-11T18:58:39.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T18:58:39.389+0000] {logging_mixin.py:137} INFO - [2023-05-11T18:58:39.389+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T18:58:39.390+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T18:58:39.403+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.040 seconds
[2023-05-11T18:59:10.148+0000] {processor.py:153} INFO - Started process (PID=423) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T18:59:10.149+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T18:59:10.149+0000] {logging_mixin.py:137} INFO - [2023-05-11T18:59:10.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T18:59:10.161+0000] {logging_mixin.py:137} INFO - [2023-05-11T18:59:10.160+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T18:59:10.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T18:59:10.174+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.029 seconds
[2023-05-11T18:59:40.944+0000] {processor.py:153} INFO - Started process (PID=671) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T18:59:40.949+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T18:59:40.949+0000] {logging_mixin.py:137} INFO - [2023-05-11T18:59:40.949+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T18:59:40.959+0000] {logging_mixin.py:137} INFO - [2023-05-11T18:59:40.958+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T18:59:40.959+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T18:59:40.973+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.032 seconds
[2023-05-11T19:00:11.931+0000] {processor.py:153} INFO - Started process (PID=903) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:00:11.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:00:11.934+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:00:11.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:00:11.944+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:00:11.944+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:00:11.945+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:00:11.959+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.030 seconds
[2023-05-11T19:00:42.273+0000] {processor.py:153} INFO - Started process (PID=1152) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:00:42.276+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:00:42.277+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:00:42.276+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:00:42.290+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:00:42.289+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:00:42.290+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:00:42.309+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.039 seconds
[2023-05-11T19:01:12.731+0000] {processor.py:153} INFO - Started process (PID=1392) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:01:12.735+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:01:12.735+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:01:12.735+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:01:12.745+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:01:12.744+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:01:12.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:01:12.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.033 seconds
[2023-05-11T19:01:43.237+0000] {processor.py:153} INFO - Started process (PID=1633) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:01:43.238+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:01:43.238+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:01:43.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:01:43.251+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:01:43.250+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:01:43.251+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:01:43.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.034 seconds
[2023-05-11T19:02:13.865+0000] {processor.py:153} INFO - Started process (PID=1881) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:02:13.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:02:13.867+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:02:13.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:02:13.910+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:02:13.909+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:02:13.911+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:02:13.957+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.095 seconds
[2023-05-11T19:03:23.844+0000] {processor.py:153} INFO - Started process (PID=174) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:03:23.850+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:03:23.851+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:03:23.850+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:03:23.878+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:03:23.877+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:03:23.879+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:03:24.150+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.309 seconds
[2023-05-11T19:03:54.567+0000] {processor.py:153} INFO - Started process (PID=423) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:03:54.567+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:03:54.568+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:03:54.568+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:03:54.580+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:03:54.580+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:03:54.581+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:03:54.597+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.034 seconds
[2023-05-11T19:04:25.005+0000] {processor.py:153} INFO - Started process (PID=664) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:04:25.005+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:04:25.006+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:04:25.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:04:25.026+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:04:25.025+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:04:25.026+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:04:25.049+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.047 seconds
[2023-05-11T19:04:55.740+0000] {processor.py:153} INFO - Started process (PID=903) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:04:55.741+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:04:55.742+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:04:55.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:04:55.760+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:04:55.760+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:04:55.761+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:04:55.784+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.046 seconds
[2023-05-11T19:05:26.100+0000] {processor.py:153} INFO - Started process (PID=1144) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:05:26.100+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:05:26.101+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:05:26.101+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:05:26.119+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:05:26.118+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:05:26.119+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:05:26.140+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.043 seconds
[2023-05-11T19:05:56.253+0000] {processor.py:153} INFO - Started process (PID=1383) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:05:56.258+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:05:56.259+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:05:56.259+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:05:56.272+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:05:56.271+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:05:56.272+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:05:56.292+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.041 seconds
[2023-05-11T19:06:26.341+0000] {processor.py:153} INFO - Started process (PID=1624) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:06:26.343+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:06:26.344+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:06:26.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:06:26.358+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:06:26.357+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:06:26.358+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:06:26.379+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.041 seconds
[2023-05-11T19:06:57.017+0000] {processor.py:153} INFO - Started process (PID=1863) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:06:57.018+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:06:57.019+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:06:57.019+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:06:57.032+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:06:57.031+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:06:57.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:06:57.049+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.034 seconds
[2023-05-11T19:07:27.412+0000] {processor.py:153} INFO - Started process (PID=2104) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:07:27.413+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:07:27.414+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:07:27.414+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:07:27.434+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:07:27.433+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:07:27.435+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:07:27.472+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.063 seconds
[2023-05-11T19:07:57.954+0000] {processor.py:153} INFO - Started process (PID=2344) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:07:57.954+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:07:57.955+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:07:57.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:07:57.968+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:07:57.967+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:07:57.968+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:07:57.986+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.035 seconds
[2023-05-11T19:09:20.727+0000] {processor.py:153} INFO - Started process (PID=191) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:09:20.729+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:09:20.730+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:09:20.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:09:20.866+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:09:20.865+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:09:20.866+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:09:20.896+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.172 seconds
[2023-05-11T19:09:51.656+0000] {processor.py:153} INFO - Started process (PID=424) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:09:51.658+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:09:51.659+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:09:51.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:09:51.670+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:09:51.669+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:09:51.670+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:09:51.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.033 seconds
[2023-05-11T19:10:21.736+0000] {processor.py:153} INFO - Started process (PID=672) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:10:21.736+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:10:21.737+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:10:21.737+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:10:21.749+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:10:21.748+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:10:21.749+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:10:21.765+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.032 seconds
[2023-05-11T19:10:51.860+0000] {processor.py:153} INFO - Started process (PID=904) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:10:51.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:10:51.862+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:10:51.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:10:51.879+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:10:51.878+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:10:51.879+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:10:51.897+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.041 seconds
[2023-05-11T19:11:22.355+0000] {processor.py:153} INFO - Started process (PID=1152) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:11:22.357+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:11:22.358+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:11:22.358+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:11:22.368+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:11:22.367+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:11:22.368+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:11:22.382+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.029 seconds
[2023-05-11T19:13:59.971+0000] {processor.py:153} INFO - Started process (PID=192) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:13:59.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:13:59.973+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:13:59.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:14:00.028+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:14:00.027+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:14:00.028+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:14:00.056+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.087 seconds
[2023-05-11T19:14:30.939+0000] {processor.py:153} INFO - Started process (PID=425) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:14:30.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:14:30.942+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:14:30.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:14:30.954+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:14:30.954+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:14:30.955+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:14:30.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.037 seconds
[2023-05-11T19:15:01.215+0000] {processor.py:153} INFO - Started process (PID=673) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:15:01.217+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:15:01.218+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:15:01.218+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:15:01.227+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:15:01.227+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:15:01.227+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:15:01.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.028 seconds
[2023-05-11T19:15:32.204+0000] {processor.py:153} INFO - Started process (PID=905) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:15:32.206+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:15:32.207+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:15:32.207+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:15:32.220+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:15:32.219+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:15:32.220+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:15:32.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.039 seconds
[2023-05-11T19:15:47.418+0000] {processor.py:153} INFO - Started process (PID=1129) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:15:47.420+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:15:47.421+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:15:47.421+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:15:47.432+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:15:47.431+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:15:47.432+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:15:47.446+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.030 seconds
[2023-05-11T19:16:17.854+0000] {processor.py:153} INFO - Started process (PID=1367) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:16:17.855+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:16:17.856+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:16:17.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:16:17.868+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:16:17.867+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:16:17.868+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:16:17.885+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.034 seconds
[2023-05-11T19:16:47.957+0000] {processor.py:153} INFO - Started process (PID=1615) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:16:47.960+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:16:47.961+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:16:47.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:16:47.981+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:16:47.980+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:16:47.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:16:48.003+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.049 seconds
[2023-05-11T19:17:18.103+0000] {processor.py:153} INFO - Started process (PID=1848) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:17:18.106+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:17:18.107+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:17:18.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:17:18.122+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:17:18.122+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:17:18.123+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:17:18.140+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.043 seconds
[2023-05-11T19:17:25.174+0000] {processor.py:153} INFO - Started process (PID=1869) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:17:25.177+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:17:25.178+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:17:25.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:17:25.192+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:17:25.192+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:17:25.193+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:17:25.206+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.037 seconds
[2023-05-11T19:17:55.901+0000] {processor.py:153} INFO - Started process (PID=2102) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:17:55.904+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:17:55.904+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:17:55.904+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:17:55.917+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:17:55.916+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:17:55.917+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:17:55.935+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.035 seconds
[2023-05-11T19:18:26.824+0000] {processor.py:153} INFO - Started process (PID=2351) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:18:26.827+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:18:26.827+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:18:26.827+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:18:26.839+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:18:26.839+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:18:26.840+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:18:26.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.030 seconds
[2023-05-11T19:18:57.553+0000] {processor.py:153} INFO - Started process (PID=2583) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:18:57.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:18:57.557+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:18:57.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:18:57.572+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:18:57.571+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:18:57.572+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:18:57.589+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.038 seconds
[2023-05-11T19:19:27.947+0000] {processor.py:153} INFO - Started process (PID=2831) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:19:27.950+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:19:27.950+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:19:27.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:19:27.966+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:19:27.965+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:19:27.966+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:19:27.985+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.040 seconds
[2023-05-11T19:19:58.724+0000] {processor.py:153} INFO - Started process (PID=3063) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:19:58.726+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:19:58.727+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:19:58.727+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:19:58.742+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:19:58.741+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:19:58.742+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:19:58.758+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.038 seconds
[2023-05-11T19:20:29.079+0000] {processor.py:153} INFO - Started process (PID=3311) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:20:29.079+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:20:29.080+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:20:29.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:20:29.098+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:20:29.097+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:20:29.098+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:20:29.118+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.043 seconds
[2023-05-11T19:20:59.573+0000] {processor.py:153} INFO - Started process (PID=3543) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:20:59.576+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:20:59.576+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:20:59.576+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:20:59.588+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:20:59.588+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:20:59.588+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:20:59.605+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.036 seconds
[2023-05-11T19:21:30.028+0000] {processor.py:153} INFO - Started process (PID=3791) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:21:30.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:21:30.030+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:21:30.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:21:30.045+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:21:30.044+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:21:30.045+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:21:30.062+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.039 seconds
[2023-05-11T19:22:00.497+0000] {processor.py:153} INFO - Started process (PID=4023) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:22:00.500+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:22:00.500+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:22:00.500+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:22:00.513+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:22:00.513+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:22:00.514+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:22:00.530+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.035 seconds
[2023-05-11T19:22:30.657+0000] {processor.py:153} INFO - Started process (PID=4271) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:22:30.660+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:22:30.660+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:22:30.660+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:22:30.671+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:22:30.670+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:22:30.671+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:22:30.683+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.027 seconds
[2023-05-11T19:23:01.327+0000] {processor.py:153} INFO - Started process (PID=4504) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:23:01.329+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:23:01.330+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:23:01.330+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:23:01.344+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:23:01.343+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:23:01.344+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:23:01.360+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.037 seconds
[2023-05-11T19:23:31.817+0000] {processor.py:153} INFO - Started process (PID=4753) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:23:31.817+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:23:31.818+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:23:31.818+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:23:31.830+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:23:31.829+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:23:31.830+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:23:31.847+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.033 seconds
[2023-05-11T19:24:02.105+0000] {processor.py:153} INFO - Started process (PID=4985) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:24:02.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:24:02.109+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:24:02.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:24:02.125+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:24:02.124+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 11, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:24:02.125+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:24:02.142+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.039 seconds
[2023-05-11T19:24:24.706+0000] {processor.py:153} INFO - Started process (PID=5217) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:24:24.709+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:24:24.709+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:24:24.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:24:24.725+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:24:24.724+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:24:24.725+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:24:24.742+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.040 seconds
[2023-05-11T19:25:26.765+0000] {processor.py:153} INFO - Started process (PID=183) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:25:26.774+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:25:26.788+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:25:26.786+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:25:26.814+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:25:26.813+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:25:26.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:25:27.006+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.243 seconds
[2023-05-11T19:25:49.542+0000] {processor.py:153} INFO - Started process (PID=407) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:25:49.546+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:25:49.546+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:25:49.546+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:25:49.563+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:25:49.562+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:25:49.563+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:25:49.600+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.063 seconds
[2023-05-11T19:26:20.328+0000] {processor.py:153} INFO - Started process (PID=655) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:26:20.329+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:26:20.329+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:26:20.329+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:26:20.345+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:26:20.344+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:26:20.345+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:26:20.361+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.037 seconds
[2023-05-11T19:26:47.924+0000] {processor.py:153} INFO - Started process (PID=887) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:26:47.927+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:26:47.927+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:26:47.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:26:47.941+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:26:47.940+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:26:47.941+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:26:47.957+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.036 seconds
[2023-05-11T19:27:18.566+0000] {processor.py:153} INFO - Started process (PID=1135) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:27:18.572+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:27:18.573+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:27:18.573+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:27:18.593+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:27:18.593+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:27:18.594+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:27:18.610+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.049 seconds
[2023-05-11T19:27:49.502+0000] {processor.py:153} INFO - Started process (PID=1367) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:27:49.504+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:27:49.505+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:27:49.505+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:27:49.519+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:27:49.518+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:27:49.519+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:27:49.536+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.037 seconds
[2023-05-11T19:28:19.893+0000] {processor.py:153} INFO - Started process (PID=1615) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:28:19.894+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:28:19.894+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:28:19.894+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:28:19.906+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:28:19.905+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:28:19.906+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:28:19.920+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.029 seconds
[2023-05-11T19:28:49.954+0000] {processor.py:153} INFO - Started process (PID=1847) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:28:49.957+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:28:49.957+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:28:49.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:28:49.970+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:28:49.969+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:28:49.970+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:28:49.986+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.034 seconds
[2023-05-11T19:29:20.602+0000] {processor.py:153} INFO - Started process (PID=2098) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:29:20.605+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:29:20.605+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:29:20.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:29:20.619+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:29:20.618+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:29:20.619+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:29:20.630+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.031 seconds
[2023-05-11T19:29:50.916+0000] {processor.py:153} INFO - Started process (PID=2330) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:29:50.918+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:29:50.919+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:29:50.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:29:50.932+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:29:50.932+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:29:50.933+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:29:50.945+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.032 seconds
[2023-05-11T19:30:21.740+0000] {processor.py:153} INFO - Started process (PID=2578) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:30:21.741+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:30:21.742+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:30:21.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:30:21.756+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:30:21.755+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:30:21.756+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:30:21.775+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.037 seconds
[2023-05-11T19:30:51.940+0000] {processor.py:153} INFO - Started process (PID=2810) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:30:51.942+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:30:51.943+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:30:51.943+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:30:51.956+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:30:51.956+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:30:51.957+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:30:51.977+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.041 seconds
[2023-05-11T19:31:22.844+0000] {processor.py:153} INFO - Started process (PID=3058) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:31:22.846+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:31:22.847+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:31:22.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:31:22.861+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:31:22.860+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:31:22.861+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:31:22.877+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.037 seconds
[2023-05-11T19:31:53.601+0000] {processor.py:153} INFO - Started process (PID=3290) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:31:53.603+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:31:53.604+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:31:53.604+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:31:53.620+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:31:53.619+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:31:53.620+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:31:53.637+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.039 seconds
[2023-05-11T19:32:24.065+0000] {processor.py:153} INFO - Started process (PID=3537) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:32:24.066+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:32:24.067+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:32:24.066+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:32:24.080+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:32:24.079+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:32:24.080+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:32:24.097+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.034 seconds
[2023-05-11T19:32:54.445+0000] {processor.py:153} INFO - Started process (PID=3769) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:32:54.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:32:54.448+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:32:54.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:32:54.462+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:32:54.461+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:32:54.462+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:32:54.478+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.036 seconds
[2023-05-11T19:33:25.014+0000] {processor.py:153} INFO - Started process (PID=4017) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:33:25.015+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:33:25.015+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:33:25.015+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:33:25.023+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:33:25.023+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:33:25.023+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:33:25.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.023 seconds
[2023-05-11T19:35:10.060+0000] {processor.py:153} INFO - Started process (PID=190) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:35:10.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:35:10.062+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:35:10.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:35:10.084+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:35:10.083+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:35:10.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:35:10.268+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.211 seconds
[2023-05-11T19:35:41.068+0000] {processor.py:153} INFO - Started process (PID=423) to work on /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:35:41.070+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/gw2_dag.py for tasks to queue
[2023-05-11T19:35:41.071+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:35:41.071+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:35:41.080+0000] {logging_mixin.py:137} INFO - [2023-05-11T19:35:41.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/gw2_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gw2_dag.py", line 16, in <module>
    from src.url_writer import url_writer_script
ModuleNotFoundError: No module named 'src'
[2023-05-11T19:35:41.080+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/gw2_dag.py
[2023-05-11T19:35:41.095+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/gw2_dag.py took 0.030 seconds
